apiVersion: v1
kind: Pod
metadata: 
  namespace: network-test
  labels:
    app: cni-benchmark
    node: a1
  name: cni-benchmark-a1
spec:
  containers:
    - name: benchmark
      # image: hub.comcast.net/k8s-eng/iperf3:v2.8
      image: hub.comcast.net/cloud-network/statexec_iperf3:v1.0
      command: ["sleep","infinity"]
      securityContext:
        capabilities:
          add:
          - SYS_NICE
      ports:
      - containerPort: 5201
        name: iperf3
      - containerPort: 8080
        name: statexec
  nodeSelector:
    "kubernetes.io/hostname": "10.112.182.135"
--- 
apiVersion: v1
kind: Pod
metadata: 
  namespace: network-test
  labels:
    app: cni-benchmark
    node: a2
  name: cni-benchmark-a2
spec:
  containers:
    - name: benchmark
      # image: hub.comcast.net/k8s-eng/iperf3:v2.8
      image: hub.comcast.net/cloud-network/statexec_iperf3:v1.0
      command: ["sleep","infinity"]
      securityContext:
        capabilities:
          add:
          - SYS_NICE
      ports:
      - containerPort: 5201
        name: iperf3
      - containerPort: 8080
        name: statexec
  nodeSelector:
    "kubernetes.io/hostname": "10.112.182.135"
--- 
apiVersion: v1
kind: Pod
metadata: 
  namespace: network-test
  labels:
    app: cni-benchmark
    node: a3
  name: cni-benchmark-a3
spec:
  containers:
    - name: benchmark
      # image: hub.comcast.net/k8s-eng/iperf3:v2.8
      image: hub.comcast.net/cloud-network/statexec_iperf3:v1.0
      command: ["sleep","infinity"]
      securityContext:
        capabilities:
          add:
          - SYS_NICE
      ports:
      - containerPort: 5201
        name: iperf3
      - containerPort: 8080
        name: statexec
  nodeSelector:
    "kubernetes.io/hostname": "10.112.182.136"

--- 
apiVersion: v1
kind: Service
metadata:
  namespace: network-test
  name: cni-benchmark-a1
spec:
  selector:
    app: cni-benchmark
    node: a1
  ports:
  - name: iperf3
    port: 5201
    protocol: TCP
    targetPort: 5201
  - name: iperf3-udp
    port: 5201
    protocol: UDP
    targetPort: 5201
  - name: statexec
    port: 8080
    targetPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  namespace: network-test
  name: cni-benchmark-a2
spec:
  selector:
    app: cni-benchmark
    node: a2
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
  - IPv4
  - IPv6
  ports:
  - name: iperf3
    port: 5201
    protocol: TCP
    targetPort: 5201
  - name: iperf3-udp
    port: 5201
    protocol: UDP
    targetPort: 5201
  - name: statexec
    port: 8080
    targetPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  namespace: network-test
  name: cni-benchmark-a3
spec:
  selector:
    app: cni-benchmark
    node: a3
  # type: LoadBalancer
  # ipFamilyPolicy: RequireDualStack
  # ipFamilies:
  # - IPv4
  # - IPv6
  ports:
  - name: iperf3
    port: 5201
    protocol: TCP
    targetPort: 5201
  - name: iperf3-udp
    port: 5201
    protocol: UDP
    targetPort: 5201
  - name: statexec
    port: 8080
    targetPort: 8080
--- 