{
 "title": "Benchmark Results",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2024-01-01T00:01:30.600Z" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "CNI",
    "query": {
     "query": "label_values(benchmark_mem_bytes,id)"
    }
   },
   {
    "name": "test",
    "label": "Test",
    "query": "dts, dtm, dus, dum, sts, stm, sus, sum"
   },
   {
    "name": "bmfilter",
    "query": {
     "query": "label_values(statexec_memory_used_bytes{instance=\"$test\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "bandwidth detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<hr style=\"border-color: yellow\">\n<h1 style=\"color: yellow; font-size: 30px;\"> Bandwidth during test \"dtm\" for every CNI (with each run detail) </h1>"
   }
  },
  {
   "title": "[$id][$test] - Bandwidth in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "repeat": "id",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=~\"${id}\",instance=~\"$test\",role=\"client\"}[1s]) * 8) by (id,instance,run)",
     "legendFormat": "sys_bw sent ({{run}})"
    },
    {
     "expr": "sum(rate(statexec_network_received_bytes_total{id=~\"${id}\",instance=~\"$test\",role=\"server\"}[1s]) * 8) by (id,instance,run)",
     "legendFormat": "sys_bw rcvd ({{run}})"
    },
    {
     "expr": "max(\n    benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n) by (run) @ start()",
     "legendFormat": "iperf_bw result ({{run}})"
    }
   ]
  },
  {
   "title": "[$id][$test] - Bandwidth in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_packets_total{id=~\"${id}\",instance=~\"$test\",role=\"client\"}[1s])) by (id,instance,run)",
     "legendFormat": "sys_bw sent ({{run}})"
    },
    {
     "expr": "sum(rate(statexec_network_received_packets_total{id=~\"${id}\",instance=~\"$test\",role=\"server\"}[1s])) by (id,instance,run)",
     "legendFormat": "sys_bw rcvd ({{run}})"
    }
   ]
  },
  {
   "title": "cpu+mem detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "<hr style=\"border-color: yellow\">\n<h1 style=\"color: yellow; font-size: 30px;\"> CPU and Memory consumption during test \"$test\" for every CNI (with each run detail) </h1>"
     }
    },
    {
     "title": "[$id][$test] - CPU and Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "repeat": "id",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(# CPU Detail\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[1s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id,run)\n)",
       "legendFormat": "{{id}} cpu in core (run{{run}})"
      },
      {
       "expr": "max(\nstatexec_memory_used_bytes{id=~\"$id\",instance=~\"$test\"}/1Gi\n) by (id,run)",
       "legendFormat": "{{id}} mem in GB (run{{run}})"
      }
     ]
    }
   ]
  },
  { "title": "result summary table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<hr style=\"border-color: yellow\">\n<h1 style=\"color: yellow; font-size: 30px;\"> Result summary table for test \"$test\" </h1>"
   }
  },
  {
   "title": "Benchmark result for test $test",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "# Maximum bandwidth result other all runs within a benchmark for a specific test\nmax(\n    benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n) by (id) @ start()",
     "legendFormat": "bw"
    },
    {
     "expr": "(# CPU\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[40s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id)\n    # All tests run during 60s after 10s prequel and 20scd cooldown. \n    # Timerange must be beween 00:00:00 UTC and 00:01:30, on Jan the 1st of 2024\n    # Then we can take the average cpu over 40s duration, 30s before the end of the range (aka between 00:00:30 and 00:01:00)\n    @ ( end() - 30 )\n) * 1000 # Converting CPU in mCPU\n\n/\n\n(# BW in Gbit/s\n    # Maximum bandwidth result other all runs within a benchmark for a specific test\n    max(\n        benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n    ) by (id) @ start() \n    / 1G\n)",
     "legendFormat": "cpueff"
    },
    {
     "expr": "max(\navg_over_time(statexec_memory_used_bytes{id=~\"$id\",instance=~\"$test\"}[40s]) @ ( end() - 30 )\n) by (id)\n-\nmax(\navg_over_time(statexec_memory_used_bytes{id=\"baremetal\",instance=~\"d$bmfilter\"}[40s]) @ ( end() - 30 )\n)\n",
     "legendFormat": "memover"
    }
   ]
  },
  {
   "title": "resource efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "<hr style=\"border-color: yellow\">\n<h1 style=\"color: yellow; font-size: 30px;\"> Resource efficiency summary for test \"$test\" </h1>"
     }
    },
    {
     "title": "Ressources efficiency per CNI for test \"$test\"",
     "type": "xychart",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "(# CPU\n    #=== CPU per benchmark (id), test(instance), run ==================================\n    max( # Maximum of CPU over the three runs for a test (instance) of a specific CNI (id) \n        avg( # CPU average over all servers within the same run (client and server)\n            sum( # CPU sum over all cores (cpu) and mode (user/system/softirq/...) for each server of every run\n                rate(statexec_cpu_seconds_total{id=~\"$id\",instance=~\"$test\",mode!=\"idle\"}[40s])\n            ) by (id,instance,run,role)\n        ) by (id,instance,run)\n    ) by (id)\n    # All tests run during 60s after 10s prequel and 20scd cooldown. \n    # Timerange must be beween 00:00:00 UTC and 00:01:30, on Jan the 1st of 2024\n    # Then we can take the average cpu over 40s duration, 30s before the end of the range (aka between 00:00:30 and 00:01:00)\n    @ ( end() - 30 )\n) * 1000 # Converting CPU in mCPU\n\n/\n\n(# BW in Gbit/s\n    # Maximum bandwidth result other all runs within a benchmark for a specific test\n    max(\n        benchmark_iperf_bandwidth_bits_per_second{id=~\"$id\",test=\"$test\"}\n    ) by (id) @ start() \n    / 1G\n)\n\n#or label_set(0,\"id\",\"origin\")\n#or label_set(0,\"id\",\"maxX\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(\navg_over_time(statexec_memory_used_bytes{id=~\"$id\",instance=~\"$test\"}[40s]) @ ( end() - 30 )\n) by (id) \n-\nmax(avg_over_time(statexec_memory_used_bytes{id=\"baremetal\",instance=~\"d$bmfilter\"}[40s]) @ ( end() - 30 ))\n\n\n#or label_set(0,\"id\",\"origin\")\n#or label_set(1.5Gi,\"id\",\"maxX\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "Test naming : `[ds][tu][sm]`\n- `[ds]` : Direct mode (ip to ip) or via Service (pod to service)\n- `[tu]` : Tcp or Udp protocol\n- `[sm]` : Single stream or Multi streams (8 threads iperf3)\n\nExemples: `dus` stands for Direct Udp Singlestream, `stm` is Service Tcp Multistream\n\n---\n\nRepo: https://github.com/InfraBuilder/benchmark-k8s-cni-2024-01/\n\nTwitter : [@infrabuilder](https://twitter.com/infrabuilder) - [@BlackSwiftFR](https://twitter.com/blackswiftfr)\n\nWeb : [www.infraBuilder.com](https://www.infrabuilder.com) - [www.BlackSwift.fr](https://www.blackswift.fr)"
   }
  }
 ]
}