{
 "title": "Benchmark",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2024-01-01T00:01:30.600Z" },
 "templating": {
  "list": [
   { "name": "filter", "label": "Filter" },
   {
    "name": "id_a",
    "label": "Benchmark id A",
    "query": {
     "query": "label_values(benchmark_mem_bytes,id)"
    }
   },
   {
    "name": "run_a",
    "label": "Run A",
    "query": {
     "query": "label_values(benchmark_mem_bytes{id=\"$id_b\"},run)"
    }
   },
   {
    "name": "id_b",
    "label": "Benchmark id B",
    "query": {
     "query": "label_values(benchmark_mem_bytes,id)"
    }
   },
   {
    "name": "run_b",
    "label": "Run B",
    "query": {
     "query": "label_values(benchmark_mem_bytes{id=\"$id_b\"},run)"
    }
   },
   {
    "name": "testtcp",
    "label": "TCP",
    "query": "dts_88,dts_1472,dts_8972,dts_1472_v6,dts_8972_v6,dtm_88,dtm_1472,dtm_8972,dtm_1472_v6,dtm_8972_v6,sts,stm"
   },
   { "name": "testudp", "label": "UDP", "query": "dus,dum,sus,sum" }
  ]
 },
 "panels": [
  { "title": "Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<center>\n<h1>Kubernetes CNI benchmark 2024-01</h1>\n  by infraBuilder and BlackSwift\n</center>\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "options": {
    "content": "<center><h1>Benchmark ${id_a}</h1></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "options": {
    "content": "<center><h1>Benchmark ${id_b}</h1></center>"
   }
  },
  { "title": "Result summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "[$id_a] Average Bandwidth by test",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_a}\",run=~\"${run_a}\"} ) by (test)",
     "legendFormat": "{{test}}"
    }
   ]
  },
  {
   "title": "[$id_b] Average Bandwidth by test",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_b}\",run=~\"${run_b}\"} ) by (test)",
     "legendFormat": "{{test}}"
    }
   ]
  },
  {
   "title": "[$id_a] Variance coefficient of bandwidth by test",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(benchmark_iperf_bandwidth_bits_per_second{id=~\"${id_a}\"}) by (test)\n/\navg(benchmark_iperf_bandwidth_bits_per_second{id=~\"${id_a}\"}) by (test)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_b] Variance coefficient of bandwidth by test",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(benchmark_iperf_bandwidth_bits_per_second{id=~\"${id_b}\"}) by (test)\n/\navg(benchmark_iperf_bandwidth_bits_per_second{id=~\"${id_b}\"}) by (test)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_a] Bandwidth by test with run details",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_a}\",run=~\"${run_a}\"} ) by (test,run)",
     "legendFormat": "{{test}}/{{run}}"
    }
   ]
  },
  {
   "title": "[$id_b] Bandwidth by test with run details",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=\"${id_b}\",run=~\"${run_b}\"} ) by (test,run)",
     "legendFormat": "{{test}}/{{run}}"
    }
   ]
  },
  {
   "title": "IDLE - System metrics when there is no traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$id_a][idle] - Client Throughput in bits/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"client\"}[1s]) * 8) by (run)",
       "legendFormat": "Run {{run}}"
      }
     ]
    },
    {
     "title": "[$id_a][idle] - Server Throughput in bits/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"server\"}[1s]) * 8) by (run)",
       "legendFormat": "Run {{run}}"
      }
     ]
    },
    {
     "title": "[$id_b][idle] - Client Throughput in bits/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"client\"}[1s]) * 8) by (run)",
       "legendFormat": "Run {{run}}"
      }
     ]
    },
    {
     "title": "[$id_b][idle] - Server Throughput in bits/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(statexec_network_received_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"server\"}[1s]) * 8) by (run)",
       "legendFormat": "Run {{run}}"
      }
     ]
    },
    {
     "title": "[$id_a][idle] - Client CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"client\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[$id_a][idle] - Server CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"server\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[$id_b][idle] - Client CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"client\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[$id_b][idle] - Server CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "targets": [
      {
       "expr": "sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"server\",mode!=\"idle\"}[1s])\n) by (run,mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[$id_a][idle] - Client Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"client\"} > 0\n#) by (run,mode)",
       "legendFormat": "{{run}}/{{role}}"
      }
     ]
    },
    {
     "title": "[$id_a][idle] - Server Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"idle\",role=\"server\"} > 0\n#) by (run,mode)",
       "legendFormat": "{{run}}/{{role}}"
      }
     ]
    },
    {
     "title": "[$id_b][idle] - Client Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"client\"} > 0\n#) by (run,mode)",
       "legendFormat": "{{run}}/{{role}}"
      }
     ]
    },
    {
     "title": "[$id_b][idle] - Server Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"idle\",role=\"server\"} > 0\n#) by (run,mode)",
       "legendFormat": "{{run}}/{{role}}"
      }
     ]
    }
   ]
  },
  { "title": "Tests TCP - $testtcp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "testtcp" },
  {
   "title": "[$id_a][$testtcp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_a\",test=~\"$testtcp\",run=~\"$run_a\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_retransmits_count{id=~\"$id_a\",test=~\"$testtcp\",run=~\"$run_a\"})",
     "legendFormat": "retransmits"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_b\",test=~\"$testtcp\",run=~\"$run_b\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_retransmits_count{id=~\"$id_b\",test=~\"$testtcp\",run=~\"$run_b\"})",
     "legendFormat": "retransmits"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Client Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Server Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"server\"}[1s]) * 8) by (run)\n",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Client Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Server Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"server\"}[1s]) * 8) by (run)\n",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Client Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_packets_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"client\"}[1s])) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Server Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_packets_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"server\"}[1s])) by (run)\n",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Client Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_packets_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"client\"}[1s])) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Server Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_packets_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"server\"}[1s])) by (run)\n",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Client CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Client CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Client Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"client\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testtcp] - Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testtcp\",role=\"server\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Client Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"client\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testtcp] - Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testtcp\",role=\"server\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  { "title": "Tests UDP - $testudp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 }, "repeat": "testudp" },
  {
   "title": "[$id_a][$testudp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_b\",test=~\"$testudp\",run=~\"$run_b\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_jitter_milliseconds{id=~\"$id_a\",test=~\"$testudp\",run=~\"$run_a\"})",
     "legendFormat": "Jitter"
    },
    {
     "expr": "#avg(benchmark_iperf_jitter_milliseconds{id=~\"$id_a\",test=~\"$testudp\",run=~\"$run_a\"})\navg(benchmark_iperf_lost_percent{id=~\"$id_a\",test=~\"$testudp\",run=~\"$run_a\"})",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Results average over all runs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(benchmark_iperf_bandwidth_bits_per_second{id=~\"$id_b\",test=~\"$testudp\",run=~\"$run_b\"})",
     "legendFormat": "bandwidth"
    },
    {
     "expr": "avg(benchmark_iperf_jitter_milliseconds{id=~\"$id_b\",test=~\"$testudp\",run=~\"$run_b\"})",
     "legendFormat": "Jitter"
    },
    {
     "expr": "avg(benchmark_iperf_lost_percent{id=~\"$id_b\",test=~\"$testudp\",run=~\"$run_b\"})",
     "legendFormat": "drop"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Client Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Server Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_bytes_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"server\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Client Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"client\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Server Throughput in bits/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_bytes_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"server\"}[1s]) * 8) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Client Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_packets_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"client\"}[1s])) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Server Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_packets_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"server\"}[1s])) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Client Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_sent_packets_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"client\"}[1s])) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Server Throughput in packets/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(statexec_network_received_packets_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"server\"}[1s])) by (run)",
     "legendFormat": "Run {{run}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Client CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Client CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"client\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "#sum(\nrate(statexec_cpu_seconds_total{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"server\",mode!=\"idle\"}[1s]) > 0\n#) by (run,mode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Client Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"client\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$id_a][$testudp] - Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_a}\",run=~\"${run_a}\",instance=~\"$testudp\",role=\"server\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Client Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"client\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  {
   "title": "[$id_b][$testudp] - Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "#sum(\nstatexec_memory_used_bytes{id=\"${id_b}\",run=~\"${run_b}\",instance=~\"$testudp\",role=\"server\"} > 0\n#) by (run,mode)",
     "legendFormat": "{{run}}/{{role}}"
    }
   ]
  },
  { "title": "Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 286 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 287 },
   "options": {
    "content": "Test naming : `[ds][tu][sm]`\n- `[ds]` : Direct mode (ip to ip) or via Service (pod to service)\n- `[tu]` : Tcp or Udp protocol\n- `[sm]` : Single stream or Multi streams (8 threads iperf3)\n\nExemples: `dus` stands for Direct Udp Singlestream, `stm` is Service Tcp Multistream\n\n---\n\nRepo: https://github.com/InfraBuilder/benchmark-k8s-cni-2024-01/\n\nTwitter : [@infrabuilder](https://twitter.com/infrabuilder) - [@BlackSwiftFR](https://twitter.com/blackswiftfr)\n\nWeb : [infraBuilder.com](https://infrabuilder.com) - [BlackSwift.fr](https://www.blackswift.fr)"
   }
  }
 ]
}